/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2015-06-18-d4b9e63"
#endif /* AVUTIL_FFVERSION_H */
